<%= form_with(model: cause, remote: true) do |f| %>
    <% if cause.errors.any? %>
        <div id = 'error_explanation'>
            <h2>La publicacion no se pudo crear por las siguientes razones:</h2>
            <ul>
                <% cause.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
    
    <div class="form-group">
        <%= f.label :title, "Titulo de la causa: "%>
        <%= f.text_field :title %>
    </div>

    <div class="form-group">
        <%= f.label :story, "Descripcion: " %>
        <%= f.text_field :story %>
    </div>   

    <div class="form-group">
        <%= f.label :start_date, "Fecha de inicio: " %>
        <%= f.date_field :start_date %>
    </div>  

    <div class="form-group">
        <%= f.label :end_date, "Fecha de termino: " %>
        <%= f.date_field :end_date %>
    </div>

    <div class="form-group">
        <%= f.label :reward, "Recompensa: " %>
        <%= f.text_field :reward %>
    </div>

    <div class="form-group">
        <%= f.label :project_id, "Emprendimiento: " %>
        <%= @project%>
    </div>

    <div class = 'actions'>
        <%= f.submit %>
    </div>
<% end %>